version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  server:
    container_name: python-server
    build: ./server
    ports:
      - "50051:50051"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
     - db
    volumes:
      - ./server:/app
    restart: always
    depends_on:
      - db
  client:
    container_name: python-client
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
    restart: always
    depends_on:
      - db
      - server
  
volumes:
  db:
    driver: local